### ISSUE TITLE
Function as initial value

### ISSUE THREAD

**Issue by behnammodi** [kof/react-nano-state#8]
I'm so excited, this is so simple and useful state manager.

I see something strange but I know why. if we have something like this:
```js
import { createValueContainer } from "react-nano-state";

const searchContainer = createValueContainer(() => {
  return "Type the search"
});

const SearchInput = () => {
  const [search, setSearch] = useValue(searchContainer);
 ...
};
```

`search` is `"Type the search"` but "searchContainer.value" is not `"Type the search"`

## Why?
Because we have a `useState` inside `useValue` and `useState` got a function for initial value and that suppose this is an initial function then run it.

## Solution:
Maybe we have to check `container.value` before passing it to `useState` and if it is a function we have to run it before passing it to `useState` but I'm not sure this is a good solution or not

**Comment by kof** [comment]
The api is a value as initial value, not function.

I need a very clear use case why you need a fn

**Comment by behnammodi** [comment]
Sometimes for getting a value we need to run a huge function but we need to run it when we need it:

```js
import { createValueContainer } from "react-nano-state";

function calculateSomething() {
  // return calculated value
}

const container = createValueContainer(calculateSomething);

const Component = () => {
  const [value, setValue] = useValue(container);
 ...
};
```

Also if we could pass the function we can use it as a reducer ex:
```js
import { createValueContainer } from "react-nano-state";

function counterReducer(action) {
  switch(action) {
    case 'inc': {
      return this.value + 1;
    }
    case 'dec': {
      return this.value - 1;
    }
    default {
      return this.value;
    }
  }
}

const container = createValueContainer(counterReducer);

const Component = () => {
  const [value, dispatch] = useValue(container);
  
  const handleInc = () => {
    dispatch('inc');
  };
 
  ...
};
```

**Comment by kof** [comment]
The initial value is designed to be available upfront. I think  you want to set the value you need later at render time yourself

**Comment by kof** [comment]
You are basically misusing the initial value for setting the initial value later. It's technically not an initial value at this point, it's just a value.

Imaging something tries to access the current value before you set it - it's going to be still undefined.

I am going to politely reject this request.

**Comment by behnammodi** [comment]
Thank you, This was a discussion not request

**Comment by kof** [comment]
Got it, I perceived it as request, sorry.

**Comment by behnammodi** [comment]
No problem, you're best
